name: Build TouchController
on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    env:
      MSYS_NO_PATHCONV: 1
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest ]
    steps:
      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
        with:
          fetch-depth: 0
      - name: Set up JDK 21
        uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961 # v5
        with:
          java-version: "21"
          distribution: "temurin"
      - name: Setup Android SDK
        uses: android-actions/setup-android@40fd30fb8d7440372e1316f5d1809ec01dcd3699 # v4
      - uses: nttld/setup-ndk@ed92fe6cadad69be94a966a7ee3271275e62f779 # v1.6.0
        id: setup-ndk
        with:
          ndk-version: r28b
      - name: Setup Bazel
        uses: bazel-contrib/setup-bazel@8cb04a772ab4c1eb984e9c1b493a182e96c5e425 # 0.19.0
        with:
          repository-cache: MODULE.bazel.lock
      - name: Setup Remote Cache
        uses: ./.github/actions/setup-bazel-cache
        with:
          host: ${{ vars.BAZEL_CACHE_HOST }}
          authorization: ${{ secrets.BAZEL_CACHE_AUTH }}
          downloader_cfg: ${{ vars.BAZEL_DOWNLOADER_CONFIG }}
          netrc: ${{ secrets.BAZEL_NETRC }}
      - name: Build
        run: bazel build --verbose_failures --config=opt //touchcontroller //touchcontroller/fabric //touchcontroller/neoforge
      - name: Upload artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: artifacts-${{ matrix.os }}
          path: |
            bazel-bin/touchcontroller/touchcontroller.jar
            bazel-bin/touchcontroller/fabric/fabric.jar
            bazel-bin/touchcontroller/neoforge/neoforge.jar
